### ISSUE TITLE
Can this code reproduce the results on your paper?

### ISSUE THREAD

**Issue by l11x0m7** [yanghoonkim/NQG_ASs2s#6]
Hi, 

This work is quite brilliant and it's quite helpful for me. But when I run your code with default params or some modification on hidden_size and others to keep the same description in your paper, however my bleu can only reach ~11 on dev set. How can I reproduce a relatively close result in your paper? Thanks.

**Comment by yanghoonkim** [comment]
You can almost reproduce the results on the paper, but there maybe a little difference since there is a lack of function (named-entity replacement). I guess the bleu score of the dev set you mentioned is calculated by the default code, which is an api provided by the nltk package. You have to check the bleu score with Microsoft coco captions which will give you the different score (I used the evaluation tool since previous neural question generation works has used the same tool to compare their results).

**Comment by l11x0m7** [comment]
OK, I see, thanks.

**Comment by Chevalier1024** [comment]
Hi~so have you reproduced the results on the paper? I only got a BLEU-4 score 12.957 in split1 and 13.186 in split2, that is different from in the paper(split1: 16.20, split2:16.17). @l11x0m7

**Comment by l11x0m7** [comment]
Not yet, actually I haven't tried to reproduce the result with the new bleu metric from Microsoft coco captions. @Fengfeng1024

> Hi~so have you reproduced the results on the paper? I only got a BLEU-4 score 12.957 in split1 and 13.186 in split2, that is different from in the paper(split1: 16.20, split2:16.17). @l11x0m7
